"""updated user to something workable

Revision ID: 0890e33b7617
Revises: 591f61d0417e
Create Date: 2020-07-05 03:14:41.972019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0890e33b7617'
down_revision = '591f61d0417e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unique_user_id', sa.BigInteger(), nullable=True))
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'unique_user_id')
    # ### end Alembic commands ###
