"""empty message

Revision ID: 14590a1808e4
Revises: 978e11c80295
Create Date: 2020-07-14 05:16:34.902326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14590a1808e4'
down_revision = '978e11c80295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
