"""Converted Command Record Integers to BigIntegers

Revision ID: 2551383691d9
Revises: a105fbe6eebc
Create Date: 2020-06-29 04:51:30.078218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2551383691d9'
down_revision = 'a105fbe6eebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
