"""Renamed messages_id to message_id

Revision ID: 591f61d0417e
Revises: 2551383691d9
Create Date: 2020-06-29 05:09:33.786767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591f61d0417e'
down_revision = '2551383691d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command_record', sa.Column('message_id', sa.BigInteger(), nullable=True))
    op.drop_column('command_record', 'messages_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command_record', sa.Column('messages_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('command_record', 'message_id')
    # ### end Alembic commands ###
