"""empty message

Revision ID: 5f1503cb4245
Revises: a1cf6614cfa7
Create Date: 2020-06-27 01:09:14.019644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1503cb4245'
down_revision = 'a1cf6614cfa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('channel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'channel')
    # ### end Alembic commands ###
