"""Added created at column to record

Revision ID: a105fbe6eebc
Revises: 39356c1e6711
Create Date: 2020-06-29 03:54:30.545485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a105fbe6eebc'
down_revision = '39356c1e6711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command_record', sa.Column('message_created_at', sa.DateTime(), nullable=True))
    op.drop_column('command_record', 'messaged_created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command_record', sa.Column('messaged_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('command_record', 'message_created_at')
    # ### end Alembic commands ###
