"""empty message

Revision ID: ee8e3d83e280
Revises: 0bc1728aa701
Create Date: 2020-07-10 22:47:25.574772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8e3d83e280'
down_revision = '0bc1728aa701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
